name: eudeka
description: Eudeka Indonesia (beta)
version: 0.3.1+11
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0-beta6
  firebase_auth: ^1.0.0
  hive_flutter: ^1.0.0
  provider: ^5.0.0
  url_launcher: ^6.0.2
  video_player: ^2.0.0
flutter:
  uses-material-design: true
