name: eudeka
description: Eudeka Indonesia (beta)
version: 0.1.3+8
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.5.6
  dio: ^3.0.10
  video_player: ^1.0.0
  hive_flutter: ^0.3.1
  url_launcher: ^5.7.10
flutter:
  uses-material-design: true
