name: eudeka
description: Eudeka Indonesia (beta)
version: 0.2.0+9
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  hive_flutter: ^0.3.1
  provider: ^4.3.3
  url_launcher: ^5.7.10
  video_player: ^1.0.1
flutter:
  uses-material-design: true
